# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
        backend "gcs" {
            bucket = "tf-state-pipelineformidable-bank-427016-h1"
            prefix   = "terraform/state/./terraform.tfstate"
        }
    }
